In [1]:
import pandas as pd
import glob
import re

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
psm_files = glob.glob("MSFragger_Output/*_psm.tsv")
psm_files

['MSFragger_Output\\acidorvorans_psm.tsv',
 'MSFragger_Output\\acidovorans_psm.tsv',
 'MSFragger_Output\\aurantiaca_psm.tsv',
 'MSFragger_Output\\baltica_psm.tsv',
 'MSFragger_Output\\cereus_psm.tsv',
 'MSFragger_Output\\comes_psm.tsv',
 'MSFragger_Output\\cryptum_psm.tsv',
 'MSFragger_Output\\fragilis_psm.tsv',
 'MSFragger_Output\\gilvus_psm.tsv',
 'MSFragger_Output\\gnavus_psm.tsv',
 'MSFragger_Output\\griseorubens_psm.tsv',
 'MSFragger_Output\\ljungdahlii_psm.tsv',
 'MSFragger_Output\\necator_psm.tsv',
 'MSFragger_Output\\palustris_psm.tsv',
 'MSFragger_Output\\subtilis_psm.tsv',
 'MSFragger_Output\\thermosulf_psm.tsv',
 'MSFragger_Output\\thet_psm.tsv']

In [4]:
run_files = glob.glob("MSFragger_Output/*_run.tsv")
run_files

['MSFragger_Output\\acidovorans_01_run.tsv',
 'MSFragger_Output\\acidovorans_02_run.tsv',
 'MSFragger_Output\\acidovorans_03_run.tsv',
 'MSFragger_Output\\aurantiaca_01_run.tsv',
 'MSFragger_Output\\aurantiaca_02_run.tsv',
 'MSFragger_Output\\aurantiaca_03_run.tsv',
 'MSFragger_Output\\baltica_01C_run.tsv',
 'MSFragger_Output\\baltica_01Inf_run.tsv',
 'MSFragger_Output\\baltica_02C_run.tsv',
 'MSFragger_Output\\baltica_02Inf_run.tsv',
 'MSFragger_Output\\baltica_03C_run.tsv',
 'MSFragger_Output\\baltica_03Inf_run.tsv',
 'MSFragger_Output\\cereus_01_run.tsv',
 'MSFragger_Output\\cereus_02_run.tsv',
 'MSFragger_Output\\cereus_03_run.tsv',
 'MSFragger_Output\\comes_Carb_run.tsv',
 'MSFragger_Output\\comes_Glc_run.tsv',
 'MSFragger_Output\\comes_LIB_run.tsv',
 'MSFragger_Output\\cryptum_01_run.tsv',
 'MSFragger_Output\\cryptum_02_run.tsv',
 'MSFragger_Output\\cryptum_03_run.tsv',
 'MSFragger_Output\\fragilis_01_run.tsv',
 'MSFragger_Output\\fragilis_Carb_01_run.tsv',
 'MSFragger_Output\\fragilis_CMcarb_anaerobic_01_run.tsv',
 'MSFragger_Output\\fragilis_CMcarb_anaerobic_02_run.tsv',
 'MSFragger_Output\\fragilis_CMgluc_anaerobic_01_run.tsv',
 'MSFragger_Output\\fragilis_CMgluc_anaerobic_03_run.tsv',
 'MSFragger_Output\\fragilis_LB_anaerobic_01_run.tsv',
 'MSFragger_Output\\fragilis_LB_anaerobic_02_run.tsv',
 'MSFragger_Output\\fragilis_LB_anaerobic_03_run.tsv',
 'MSFragger_Output\\fragilis_LIB_aerobic_01_run.tsv',
 'MSFragger_Output\\fragilis_LIB_aerobic_02_run.tsv',
 'MSFragger_Output\\fragilis_LIB_aerobic_03_run.tsv',
 'MSFragger_Output\\fragilis_LIB_anaerobic_01_run.tsv',
 'MSFragger_Output\\fragilis_LIB_anaerobic_02_run.tsv',
 'MSFragger_Output\\fragilis_LIB_anaerobic_03_run.tsv',
 'MSFragger_Output\\gilvus_01_run.tsv',
 'MSFragger_Output\\gilvus_02_run.tsv',
 'MSFragger_Output\\gilvus_03_run.tsv',
 'MSFragger_Output\\gnavus_run.tsv',
 'MSFragger_Output\\griseorubens_01_run.tsv',
 'MSFragger_Output\\griseorubens_02_run.tsv',
 'MSFragger_Output\\griseorubens_03_run.tsv',
 'MSFragger_Output\\ljungdahlii_CO_anaerobic_01_run.tsv',
 'MSFragger_Output\\ljungdahlii_CO_anaerobic_02_run.tsv',
 'MSFragger_Output\\ljungdahlii_CO_anaerobic_03_run.tsv',
 'MSFragger_Output\\ljungdahlii_Fructose_anaerobic_01_run.tsv',
 'MSFragger_Output\\ljungdahlii_Fructose_anaerobic_02_run.tsv',
 'MSFragger_Output\\ljungdahlii_Fructose_anaerobic_03_run.tsv',
 'MSFragger_Output\\necator_01_run.tsv',
 'MSFragger_Output\\necator_02_run.tsv',
 'MSFragger_Output\\necator_03_run.tsv',
 'MSFragger_Output\\palustris_PMnitro_anaerobic_01_run.tsv',
 'MSFragger_Output\\palustris_PMnitro_anaerobic_02_run.tsv',
 'MSFragger_Output\\palustris_PMnitro_anaerobic_03_run.tsv',
 'MSFragger_Output\\palustris_PMnonnitro_anaerobic_01_run.tsv',
 'MSFragger_Output\\palustris_PMnonnitro_anaerobic_02_run.tsv',
 'MSFragger_Output\\palustris_PMnonnitro_anaerobic_03_run.tsv',
 'MSFragger_Output\\palustris_PM_aerobic_01_run.tsv',
 'MSFragger_Output\\palustris_PM_aerobic_02_run.tsv',
 'MSFragger_Output\\palustris_PM_aerobic_03_run.tsv',
 'MSFragger_Output\\subtilis_01_run.tsv',
 'MSFragger_Output\\subtilis_02_run.tsv',
 'MSFragger_Output\\subtilis_03_run.tsv',
 'MSFragger_Output\\thermosulf_01_run.tsv',
 'MSFragger_Output\\thermosulf_02_run.tsv',
 'MSFragger_Output\\thermosulf_03_run.tsv',
 'MSFragger_Output\\thet_Carb_01_run.tsv',
 'MSFragger_Output\\thet_CMcarb_anaerobic_01_run.tsv',
 'MSFragger_Output\\thet_CMcarb_anaerobic_02_run.tsv',
 'MSFragger_Output\\thet_CMcarb_anaerobic_03_run.tsv',
 'MSFragger_Output\\thet_CMgluc_anaerobic_01_run.tsv',
 'MSFragger_Output\\thet_CMgluc_anaerobic_02_run.tsv',
 'MSFragger_Output\\thet_CMgluc_anaerobic_03_run.tsv',
 'MSFragger_Output\\thet_Glc_01_run.tsv',
 'MSFragger_Output\\thet_LB_anaerobic_01_run.tsv',
 'MSFragger_Output\\thet_LB_anaerobic_02_run.tsv',
 'MSFragger_Output\\thet_LB_anaerobic_03_run.tsv',
 'MSFragger_Output\\thet_LIB_anaerobic_01_run.tsv',
 'MSFragger_Output\\thet_LIB_anaerobic_02_run.tsv',
 'MSFragger_Output\\thet_LIB_anaerobic_03_run.tsv']

In [5]:
def extract_scannum(Spectrum):
    pattern = r'\.\d*\.'
    lst = []
    for s in Spectrum:
        m = re.search(pattern, s)
        if m:
            m = m[0]
            m = m.replace('.', '')
            m = int(m)
            lst.append(m)
        else:
            lst.append(None)
    return (lst)

In [6]:
def combine_run_files(files):
    dfs = []
    for file in files:
        name = re.split('_run.tsv', file)
        name = name[0]
        pattern = r"\\"
        name = re.split(pattern, name)
        name = name[1]
        name = re.split('_', name)
        name = name[0]
        df = pd.read_csv(file, sep = '\t')
        keeps = ['scannum', 'best_locs', 'peptide']
        df = df[df.best_locs.notnull()]
        df = df[keeps]
        df['Organism'] = [name] * len(df)
        df = df.rename(columns = {'peptide': 'Peptide'})
        dfs.append(df)
    dfs = pd.concat(dfs)
    return (dfs)

In [7]:
def combine_psm_files(files):
    dfs = []
    i = 0
    for file in files:
        name = re.split('_psm.tsv', file)
        name = name[0]
        pattern = r"\\"
        name = re.split(pattern, name)
        name = name[1]
        keeps = ['scannum', 'Peptide', 'Observed Modifications', 'Protein ID', 'Gene', 'Delta Mass']
        df = pd.read_csv(file, sep = '\t')   
        df = df[df['PeptideProphet Probability'] >=0.99]
        df = df[df['Observed Modifications'].notnull()]
        df = df[df.Gene.notnull()]
        df = df[~df.Gene.str.contains('Daci')]
        df['scannum'] = extract_scannum(df.Spectrum)
        df = df[keeps]
        df['Organism'] = [name] * len(df)        
        dfs.append(df)
    df = pd.concat(dfs)
    return(df)

In [8]:
combinded_psm_df = combine_psm_files(psm_files)
combined_run_df = combine_run_files(run_files)

C:\Users\nanel\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3263: DtypeWarning: Columns (31,32) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):
C:\Users\nanel\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3263: DtypeWarning: Columns (24) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [9]:
df = pd.merge(combinded_psm_df, combined_run_df, how='inner')
df.to_csv('Modified Peptides.csv')
df

,scannum,Peptide,Observed Modifications,Protein ID,Gene,Delta Mass,Organism,best_locs
0,1982,AAASSTAAAKTPAKR,"Asn->Gln(14.015650), Asp->Glu(14.015650), Gly-...",A9BMX9,rpoD,14.0139,acidovorans,AAASSTAAAkTPAKR
1,2020,AAASSTAAAKTPAKR,"Ala->Val(28.031300), Cys->Met(28.031300), Delt...",A9BMX9,rpoD,28.0293,acidovorans,AAASSTAAAktpakR
2,2040,AASAAAPAAGKKPAAK,"Ala->Val(28.031300), Cys->Met(28.031300), Delt...",A9BWE0,rsfS,28.0351,acidovorans,AASAAAPAAGkkpaaK
3,2046,KPMVGNNVSHANNK,"Ala->Ser(15.994915), Oxidation(15.994915), Phe...",A9BNU9,rpmB,15.9980,acidovorans,KPmVGNNVSHANNK
4,2148,AAASSTAAAKTPAK,"Asn->Gln(14.015650), Asp->Glu(14.015650), Gly-...",A9BMX9,rpoD,14.0148,acidovorans,AAASSTAAAktPAK
...,...,...,...,...,...,...,...,...
142141,53487,MVPPPLAFEVLDAVMEKLPGFPIVLHGSSSVPEEEVETINK,Tyr->Met(-32.022844),Q8A734,BT_1691,-32.0228,thet,MVPPPLAFEVLDavmeklPGFPIVLHGSSSVPEEEVETINK
142142,53502,NMVTGAAQMDGAIIVCAATDGPMPQTR,Xle->Gly(-56.062600),Q8A463,tuf,-56.0601,thet,NMVTGAAQMDGAIivcaATDGPMPQTR
142143,53503,CFFIELSEIITGK,"Ammonia-loss(-17.026549), Gln->pyro-Glu(-17.02...",Q8A017,BT_4204,-17.0259,thet,cfFIELSEIITGK
142144,53516,QEVAQDIINHLVAVLTH,"Ammonia-loss(-17.026549), Gln->pyro-Glu(-17.02...",Q8A812,coaBC,-17.0219,thet,qevAQDIINHLVAVLTH
142145,53554,IQLYCNQVYVTDSVEGIVPDFLTLLHGVIDSPDIPLNVSR,Arg->Thr(-55.053433),Q8A9B8,htpG,-55.0589,thet,IQLycnqvyvtdsvegiVPDFLTLLHGVIDSPDIPLNVSR

In [10]:
df.iloc[0:2]

,scannum,Peptide,Observed Modifications,Protein ID,Gene,Delta Mass,Organism,best_locs
0,1982,AAASSTAAAKTPAKR,"Asn->Gln(14.015650), Asp->Glu(14.015650), Gly-...",A9BMX9,rpoD,14.0139,acidovorans,AAASSTAAAkTPAKR
1,2020,AAASSTAAAKTPAKR,"Ala->Val(28.031300), Cys->Met(28.031300), Delt...",A9BMX9,rpoD,28.0293,acidovorans,AAASSTAAAktpakR

In [11]:
list(df.iloc[0:2]['Observed Modifications'])

['Asn->Gln(14.015650), Asp->Glu(14.015650), Gly->Ala(14.015650), Methyl(14.015650), Ser->Thr(14.015650), Val->Xle(14.015650)',
 'Ala->Val(28.031300), Cys->Met(28.031300), Delta:H(4)C(2)(28.031300), Dimethyl(28.031300), Ethyl(28.031300)']

In [12]:
genes = df[['Gene', 'Organism']]
genes = genes.drop_duplicates()
genes = genes.groupby('Gene').count()
genes = pd.DataFrame(genes)
gene_count = genes.copy()

In [13]:
num_organisms = pd.unique(gene_count.Organism)
num_genes = []
for i in num_organisms:
    s = sum(gene_count.Organism >= i)
    num_genes.append(s)
gene_counts = pd.DataFrame({'Number of Organisms': num_organisms, 'Number of Genes': num_genes})
gene_counts.sort_values(by = 'Number of Organisms', axis = 0)

    Number of Organisms  Number of Genes
2                     1             6622
3                     2              627
1                     3              450
4                     4              343
5                     5              261
9                     6              218
0                     7              170
12                    8              142
10                    9              124
11                   10              108
7                    11               88
6                    12               68
8                    13               47
13                   14               27
14                   15               11
15                   16                1

In [14]:
genes = genes[genes.Organism >= 5]
genes = genes.index
homologous_genes = df[['Gene', 'Organism']]
homologous_genes = homologous_genes.drop_duplicates()
homologous_genes = homologous_genes[homologous_genes.Gene.isin(genes)]
homologous_genes.to_csv('Homologous_genes.csv')
homologous_genes.head()

    Gene     Organism
0   rpoD  acidovorans
2   rsfS  acidovorans
6   infB  acidovorans
9   rpsF  acidovorans
10  nusG  acidovorans